# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(default=1111111111111111)),
                ('account_id_shaba', models.IntegerField(default=111111111111)),
                ('remain', models.IntegerField(default=100000)),
                ('lock', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(default='tehran', max_length=50)),
                ('city', models.CharField(default='tehran', max_length=50)),
                ('location', models.TextField()),
                ('account_id', models.ManyToManyField(blank=True, to='main_admin.account')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('nation_ID', models.IntegerField(default=111111111111)),
                ('sex', models.CharField(max_length=8)),
                ('cellphone_number', models.CharField(max_length=50)),
                ('tellphone_number', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('employee_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='manager_id',
            field=models.ManyToManyField(blank=True, to='main_admin.staff'),
        ),
    ]
