# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='sood',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
