# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 20:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_admin', '0002_branch_sood'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='branch',
            name='account_id',
        ),
        migrations.AddField(
            model_name='branch',
            name='account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_admin.account'),
        ),
        migrations.RemoveField(
            model_name='branch',
            name='manager_id',
        ),
        migrations.AddField(
            model_name='branch',
            name='manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_admin.staff'),
        ),
    ]
