# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0003_auto_20170131_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='branch_in',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
