# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0004_staff_branch_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_type', models.CharField(max_length=200)),
                ('t_date', models.DateField(auto_now_add=True)),
                ('t_time', models.TimeField(auto_now_add=True)),
                ('t_message', models.CharField(max_length=400)),
                ('t_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_admin.account')),
                ('t_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_admin.branch')),
                ('t_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_admin.staff')),
            ],
        ),
    ]
