# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0005_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='t_message',
            field=models.TextField(max_length=400),
        ),
    ]
