# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0007_auto_20170205_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='t_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='t_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
