# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0012_atm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atm',
            old_name='a_1000',
            new_name='a_100000',
        ),
        migrations.RenameField(
            model_name='atm',
            old_name='a_2000',
            new_name='a_20000',
        ),
        migrations.RenameField(
            model_name='atm',
            old_name='a_5000',
            new_name='a_500000',
        ),
    ]
