# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=50)),
                ('cellphone_number', models.CharField(max_length=50)),
                ('tellphone_number', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('nation_ID', models.IntegerField(default=111111111111)),
                ('account_id', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main_admin.account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
