# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_account_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.IntegerField(blank=True)),
                ('dar_vajh', models.CharField(max_length=200)),
                ('is_used', models.BooleanField(default=False)),
                ('user_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_account')),
            ],
        ),
    ]
