# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170204_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='dar_vajh',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='pay',
            field=models.IntegerField(null=True),
        ),
    ]
